server:
  port: 8080

#?????? ?????????????? ?????
spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/GB_Shop
      username: postgres
      password: root
      driver-class-name: org.postgresql.Driver

    jpa:
#?????????? ? ??????? ??? sql
      show-sql: true
      properties:
        hibernate:
#??????????? ???
        format_sql: true



